# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16rLQobLk_kvGLGHWdc0m-bUBt9tH8wST
"""

import gradio as gr
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

MODEL_PATH = "./model/my_emotion_model"

tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)
model = AutoModelForSequenceClassification.from_pretrained(MODEL_PATH)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

def predict_emotion(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=64)
    inputs = {k: v.to(device) for k, v in inputs.items()}
    with torch.no_grad():
        outputs = model(**inputs)
    pred_class = outputs.logits.argmax().item()
    emotions = {0: "sadness", 1: "joy", 2: "love", 3: "anger", 4: "fear", 5: "surprise"}
    return emotions[pred_class]

demo = gr.Interface(
    fn=predict_emotion,
    inputs=gr.Textbox(label="Enter your text", lines=2),
    outputs=gr.Textbox(label="Predicted Emotion"),
    title="Emotion Classifier from Text",
    description="Model trained on 20k tweets, fine-tuned DistilBERT. Accuracy ~94%."
)

if __name__ == "__main__":
    demo.launch(share=True)